"""CH085 - a decorator's inner wrapper function calls the wrapped callable
but isn't decorated with ``@functools.wraps``, and has no equivalent
identity-preservation of its own.

Without it, the decorated function silently loses its own identity:
`wrapper.__name__`, `__doc__`, `__module__` and `__wrapped__` all become
the wrapper's, not the original function's. Nothing raises - tracebacks
show `wrapper` instead of the real function name, `help()` and
autogenerated API docs show the wrapper's (usually empty) docstring, and
anything that introspects the function by name (a registry keyed on
`__name__`, a test runner listing test names, `functools.singledispatch`)
silently breaks or misattributes it.

The shape this looks for: an outer function whose *first* parameter is
the thing being decorated (the idiomatic `def decorator(func):` /
`def decorator(fn):` convention - required after the corpus turned up
`env_list_with_choices(env_name, default, choices, case_sensitive)` in
vllm, whose inner function calls `choices()`, a *later* parameter that's
just a validator being invoked, not anything being wrapped; treating
"calls any outer param" as the signal flagged that too), defining exactly
one inner function that calls that first parameter *in its own top-level
statements*, forwarding at least one of the inner function's own
parameters to it unchanged - `*args`/`**kwargs` unpacked straight
through, or a same-named argument passed as-is (a second corpus pass
found `_get_tiktoken_count_function(encode_length, chunk_size)`'s
`count_tokens(text)` calling `encode_length(text[start:start+chunk_size])`
- a real, differently-named, differently-behaved function that merely
*uses* `encode_length` as an ingredient, not a transparent stand-in for
it; nothing about `count_tokens` losing `encode_length`'s `__name__`
would even make sense, since `count_tokens` already has its own, chosen
name). Not through a further-nested function either (the first corpus
pass found a decorator-with-arguments pattern, three levels deep, where
this call check needs to stay scoped to the level that's actually being
evaluated, or it misattributes an innermost wrapper's calls up to its own
parent, which is just a factory and never needs @wraps itself). And it
must be *directly* returned by the outer function - `return wrapper`, or
a ternary/boolop choosing between names, but not merely referenced
somewhere inside a larger returned expression (llama_index's
`get_function_tool` passes its inner `model_fn` as `fn=model_fn` into a
`FunctionTool.from_defaults(...)` call that already takes `name=`/
`description=` explicitly - `model_fn`'s own `__name__`/`__doc__` are
never consulted, so nothing is actually lost).

Two other real, equivalent ways of preserving identity are excluded: a
manual `wrapper.__name__ = ...` (found in agno's `make_bound_method`,
which builds `__name__`/`__doc__` by hand instead of decorating), and a
call to `functools.update_wrapper(wrapper, func)` - or a same-shaped
custom helper wrapping it - anywhere in the outer function (found in
mlflow's autologging safety wrappers, which return
`update_wrapper_extended(safe_function, function)` instead of decorating).
"""

from __future__ import annotations

import ast

from codehound.core import Check, Finding

_IDENTITY_ATTRS = {"__name__", "__doc__", "__module__", "__qualname__", "__wrapped__"}


def _is_wraps_decorator(dec: ast.expr) -> bool:
    target = dec.func if isinstance(dec, ast.Call) else dec
    if isinstance(target, ast.Name):
        return target.id == "wraps"
    if isinstance(target, ast.Attribute):
        return target.attr == "wraps"
    return False


def _decorator_call_receives(dec: ast.expr, wrapped: str) -> bool:
    """`@helper(func)` on the inner wrapper - the `wraps(func)` shape under
    another name. trio's `@_wraps_async(fn)` calls `update_wrapper(wrapper,
    fn)` itself; a decorator factory handed the wrapped callable is there to
    copy its identity onto the wrapper."""
    return isinstance(dec, ast.Call) and any(
        isinstance(a, ast.Name) and a.id == wrapped for a in dec.args
    )


def _iter_own_scope(node: ast.AST):
    """Yield every descendant of `node` except ones inside a nested
    function/lambda/class - so a call buried in a further-nested inner
    function isn't mistaken for something `node` itself does."""
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda, ast.ClassDef)):
            continue
        yield child
        yield from _iter_own_scope(child)


def _inner_own_param_names(inner: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    a = inner.args
    names = {arg.arg for arg in (*a.posonlyargs, *a.args, *a.kwonlyargs)}
    if a.vararg:
        names.add(a.vararg.arg)
    if a.kwarg:
        names.add(a.kwarg.arg)
    return names


def _is_passthrough_call(call: ast.Call, own_params: set[str]) -> bool:
    for arg in call.args:
        if isinstance(arg, ast.Name) and arg.id in own_params:
            return True
        if isinstance(arg, ast.Starred) and isinstance(arg.value, ast.Name) and arg.value.id in own_params:
            return True
    for kw in call.keywords:
        if isinstance(kw.value, ast.Name) and kw.value.id in own_params:
            return True
    return False


def _calls_name_with_passthrough(inner: ast.FunctionDef | ast.AsyncFunctionDef, name: str) -> bool:
    own_params = _inner_own_param_names(inner)
    for n in _iter_own_scope(inner):
        call = n.value if isinstance(n, ast.Await) else n
        if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Name) and call.func.id == name):
            continue
        if _is_passthrough_call(call, own_params):
            return True
    return False


def _is_direct_name(value: ast.expr, name: str) -> bool:
    """True if `value` IS `name` - directly, or through a ternary/boolop
    choosing between names - not merely somewhere inside a larger
    expression (e.g. as one keyword argument of an unrelated call)."""
    if isinstance(value, ast.Name):
        return value.id == name
    if isinstance(value, ast.IfExp):
        return _is_direct_name(value.body, name) or _is_direct_name(value.orelse, name)
    if isinstance(value, ast.BoolOp):
        return any(_is_direct_name(v, name) for v in value.values)
    return False


def _is_returned(outer: ast.FunctionDef | ast.AsyncFunctionDef, name: str) -> bool:
    for node in ast.walk(outer):
        if isinstance(node, ast.Return) and node.value is not None and _is_direct_name(node.value, name):
            return True
    return False


def _has_manual_identity_preservation(outer: ast.FunctionDef | ast.AsyncFunctionDef, name: str) -> bool:
    for node in ast.walk(outer):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if (
                    isinstance(target, ast.Attribute)
                    and isinstance(target.value, ast.Name)
                    and target.value.id == name
                    and target.attr in _IDENTITY_ATTRS
                ):
                    return True
        if isinstance(node, ast.Call):
            func = node.func
            is_update_wrapper = (isinstance(func, ast.Name) and "update_wrapper" in func.id) or (
                isinstance(func, ast.Attribute) and "update_wrapper" in func.attr
            )
            if is_update_wrapper and node.args and isinstance(node.args[0], ast.Name) and node.args[0].id == name:
                return True
    return False


class DecoratorMissingFunctoolsWraps(Check):
    code = "CH085"
    name = "decorator-missing-functools-wraps"
    description = "A decorator's inner wrapper calls the wrapped function but has no @functools.wraps (or equivalent) - loses __name__/__doc__ silently."

    def run(self, tree: ast.AST, parents: dict, path: str) -> list[Finding]:
        findings: list[Finding] = []
        for outer in ast.walk(tree):
            if not isinstance(outer, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            params = [a.arg for a in outer.args.args]
            if not params:
                continue
            inners = [
                stmt for stmt in outer.body if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef))
            ]
            if len(inners) != 1:
                continue
            inner = inners[0]
            wrapped_param = params[0]
            if not _calls_name_with_passthrough(inner, wrapped_param):
                continue
            if not _is_returned(outer, inner.name):
                continue
            if any(_is_wraps_decorator(d) for d in inner.decorator_list):
                continue
            if any(_decorator_call_receives(d, wrapped_param) for d in inner.decorator_list):
                continue
            if _has_manual_identity_preservation(outer, inner.name):
                continue
            findings.append(
                Finding(
                    path=path,
                    line=inner.lineno,
                    col=inner.col_offset,
                    code=self.code,
                    message=(
                        f"`{inner.name}` calls `{wrapped_param}` and is returned by "
                        f"`{outer.name}` - this is a decorator, but `{inner.name}` has no "
                        f"@functools.wraps({wrapped_param}), so the decorated function "
                        f"silently loses its own __name__/__doc__/__module__."
                    ),
                )
            )
        return findings
